/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.AppFactura.Vistas.Compras;

import com.AppFactura.Controllers.CompraDao;
import com.AppFactura.Controllers.ProductosDao;
import com.AppFactura.Controllers.ProveedorDao;
import com.AppFactura.Personalizaciones.Ajustes;
import com.AppFactura.Vistas.MenuPrincipal.FR_MenuPrincipal;
import com.AppFactura.Vistas.Productos.FR_Add_Productos;
import com.AppFactura.Vistas.Proveedores.FR__Lista_Proveedores;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.edisoncor.gui.button.ButtonRound;

/**
 *
 * @author Adrian
 */
public class FR_Ingreso_Productos extends javax.swing.JDialog {
private int eje_X,eje_Y,filaSeleccionado;Point p;ButtonRound botonListar = new ButtonRound();
private int filaDetalle;
ProveedorDao daoProveedor = new ProveedorDao();
ProductosDao daoProductos = new ProductosDao();
CompraDao daoCompras = new CompraDao();
Ajustes confins= new Ajustes();

/***************************** variables ******************/
int ID;String descripcion;int cantidad;double precioCompra;double importe=0.00;
ButtonRound botonQuitar = new ButtonRound();
String serieCompra;String RUC;
 
/************** Modelo de tablas ********************/
    DefaultTableModel modelProductos;
    
    DefaultTableModel modelDetalleCompra;

/***********************************************

/**
 * Llamamos a la clase Ajustes
 */
    Ajustes confis = new Ajustes();
    
    /**
     * Creates new form FR_Ingreso_Productos
     */
    public FR_Ingreso_Productos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();initCompras();
    }
   private void initCompras(){
       setResizable(false);
       setLocationRelativeTo(null);
       PersonalizaTable();botonListar.setText("Listar");botonListar.setBackground(Color.red);
       botonListar.setName("listar");
       modelProductos = (DefaultTableModel) tablaProductos.getModel();
       tablaProductos.setModel(modelProductos);
       modelDetalleCompra = (DefaultTableModel) TablaDetalle.getModel();
       TablaDetalle.setModel(modelDetalleCompra);
       confis.DefectPreviewFoto(labelFoto,30,30);
       mostrarProductos();
       tablaProductos.setRowHeight(36);
       confins.HiddenColumnTable(tablaProductos, 1);
       botonQuitar.setText("Quitar");botonQuitar.setBackground(Color.red);
       botonQuitar.setName("bq");
       TablaDetalle.setRowHeight(34);
       lblUsuarioAlmacen.setText(FR_MenuPrincipal.USUARIOCONECT);
       
   }
   
   private void OcultarColumaEditDeleteProveedor(){
   confins.HiddenColumnTable(FR__Lista_Proveedores.TablaProveedores, 5);
   confins.HiddenColumnTable(FR__Lista_Proveedores.TablaProveedores, 6);
   }
   private void mostrarProductos(){
   daoProductos.ViewProductos(modelProductos, tablaProductos, botonListar);
   }
   private void PersonalizaTable(){
   /**
    * Tabla de lista de Productos
    */    
   tablaProductos.getTableHeader().setBackground(Color.GREEN);
   tablaProductos.getTableHeader().setForeground(Color.black);
   tablaProductos.getTableHeader().setFont(new Font("Arial", 16, 16));
   tablaProductos.getTableHeader().setPreferredSize(new Dimension(43, 43));
   /**
    * Tabla de detalle de compra
    */
   TablaDetalle.getTableHeader().setBackground(Color.white);
   TablaDetalle.getTableHeader().setForeground(Color.black);
   TablaDetalle.getTableHeader().setFont(new Font("Arial", 14, 14));
   TablaDetalle.getTableHeader().setPreferredSize(new Dimension(35, 35));
   
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuarioAlmacen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_serie = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtRucProveedor = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel5 = new javax.swing.JLabel();
        lblProveedorData = new javax.swing.JLabel();
        btnSeleccionarProveedor = new org.edisoncor.gui.button.ButtonRound();
        panelProductos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarProducto = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnNuevoProducto = new org.edisoncor.gui.button.ButtonRound();
        PanelDetalleCompra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDetalle = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new org.edisoncor.gui.button.ButtonColoredAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        jLabel10 = new javax.swing.JLabel();
        lblGasto = new javax.swing.JLabel();
        DatosDetalleCompra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPVenta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPCosto = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jLabel9 = new javax.swing.JLabel();
        txtUnidades = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppFactura/Imagenes/carrito.png"))); // NOI18N
        jLabel1.setText("  Ingreso Productos Almacén ");

        lblSalir.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 0, 0));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setToolTipText("Cerrar Ventana");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jefe Almacén  : ");

        lblUsuarioAlmacen.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblUsuarioAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioAlmacen.setText("Rosales Cadillo, Abelardo Adrian");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("# SERIE ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblUsuarioAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_serie)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos del Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("# RUC | RAZÓN SOCIAL : ");

        txtRucProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRucProveedor.setToolTipText("RUC | RAZÓN SOCIAL");
        txtRucProveedor.setDescripcion("BUSQUE POR RUC | RAZÓN SOCIAL");
        txtRucProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRucProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucProveedorKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Proveedor : ");

        lblProveedorData.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblProveedorData.setForeground(new java.awt.Color(51, 0, 153));
        lblProveedorData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSeleccionarProveedor.setBackground(new java.awt.Color(0, 255, 102));
        btnSeleccionarProveedor.setText("Seleccionar");
        btnSeleccionarProveedor.setToolTipText("Seleccionar Proveedor");
        btnSeleccionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRucProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProveedorData, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSeleccionarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblProveedorData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(btnSeleccionarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Listado de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppFactura/Imagenes/lupa busqueda.png"))); // NOI18N
        jLabel7.setText("Buscar : ");

        txtBuscarProducto.setDescripcion("Busque por código | descripicón | Categoría");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "ID", "Categoría", "Descripción", "Listar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablaProductos.getColumnModel().getColumn(3).setResizable(false);
            tablaProductos.getColumnModel().getColumn(3).setPreferredWidth(320);
            tablaProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnNuevoProducto.setBackground(new java.awt.Color(0, 255, 102));
        btnNuevoProducto.setText("nuevo+");
        btnNuevoProducto.setToolTipText("nuevo producto");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        PanelDetalleCompra.setBackground(new java.awt.Color(255, 255, 255));
        PanelDetalleCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Productos a Ingresar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(102, 0, 204))); // NOI18N

        TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Cantidad", "P.Compra (S/.)", "Importe", "Quitar"
            }
        ));
        TablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDetalleMouseClicked(evt);
            }
        });
        TablaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaDetalleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaDetalleKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDetalle);
        if (TablaDetalle.getColumnModel().getColumnCount() > 0) {
            TablaDetalle.getColumnModel().getColumn(1).setPreferredWidth(300);
            TablaDetalle.getColumnModel().getColumn(2).setPreferredWidth(100);
            TablaDetalle.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204), new java.awt.Color(102, 0, 204)));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setText("Guardar ");
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppFactura/Imagenes/carrito.png"))); // NOI18N
        jLabel10.setText("Total  Gasto (S/. ) : ");

        lblGasto.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lblGasto.setForeground(new java.awt.Color(0, 204, 51));
        lblGasto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGasto.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        DatosDetalleCompra.setBackground(new java.awt.Color(255, 255, 255));
        DatosDetalleCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos de Detalle Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("P. Venta (S/) : ");

        lblPVenta.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        lblPVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPVenta.setText("0.00");
        lblPVenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("P. Costo  (S/.) : ");

        lblPCosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblPCosto.setDescripcion("0.00");
        lblPCosto.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        lblPCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblPCostoKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 102));
        jLabel9.setText("Unidades  : ");

        txtUnidades.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUnidades.setDescripcion("0");
        txtUnidades.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        txtUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnidadesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout DatosDetalleCompraLayout = new javax.swing.GroupLayout(DatosDetalleCompra);
        DatosDetalleCompra.setLayout(DatosDetalleCompraLayout);
        DatosDetalleCompraLayout.setHorizontalGroup(
            DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosDetalleCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosDetalleCompraLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DatosDetalleCompraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosDetalleCompraLayout.setVerticalGroup(
            DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosDetalleCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DatosDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosDetalleCompraLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(DatosDetalleCompraLayout.createSequentialGroup()
                        .addComponent(txtUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        labelFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelDetalleCompraLayout = new javax.swing.GroupLayout(PanelDetalleCompra);
        PanelDetalleCompra.setLayout(PanelDetalleCompraLayout);
        PanelDetalleCompraLayout.setHorizontalGroup(
            PanelDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDetalleCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DatosDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDetalleCompraLayout.setVerticalGroup(
            PanelDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleCompraLayout.createSequentialGroup()
                .addGroup(PanelDetalleCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleCompraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DatosDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
    eje_X = evt.getX();
    eje_Y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
    p= MouseInfo.getPointerInfo().getLocation();
    this.setLocation(p.x-eje_X, p.y-eje_Y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
    dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void btnSeleccionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProveedorActionPerformed
     FR__Lista_Proveedores listaProveedores = new FR__Lista_Proveedores(null, rootPaneCheckingEnabled);
     OcultarColumaEditDeleteProveedor();
     listaProveedores.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProveedorActionPerformed

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
    FR_Add_Productos productosAdd = new FR_Add_Productos(null, rootPaneCheckingEnabled);
    productosAdd.setVisible(true);
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void txtRucProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucProveedorKeyTyped
    confins.lengthCadena(txtRucProveedor.getText(), 11, evt);
    boolean isLetterIsDigt = Character.isLetter(evt.getKeyChar());
    confins.isDigit_isLetter(isLetterIsDigt, evt);
    }//GEN-LAST:event_txtRucProveedorKeyTyped

    private void txtRucProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucProveedorKeyReleased
    daoProveedor.show(lblProveedorData, txtRucProveedor.getText());
    }//GEN-LAST:event_txtRucProveedorKeyReleased

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        filaSeleccionado = tablaProductos.getSelectedRow();
        try {
        if(confins.BotonDinamico(tablaProductos, evt).getName().equals("listar")){
       ID=Integer.parseInt(tablaProductos.getValueAt(filaSeleccionado, 0).toString());
       lblPCosto.setText("");txtUnidades.setText("");lblPCosto.grabFocus();
       descripcion = tablaProductos.getValueAt(filaSeleccionado, 3).toString();
       daoProductos.showData(labelFoto,lblPVenta,ID,descripcion);
       lblPCosto.grabFocus();
        }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void txtUnidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesKeyTyped
    boolean valor = Character.isLetter(evt.getKeyChar());
    confins.isDigit_isLetter(valor, evt);
    }//GEN-LAST:event_txtUnidadesKeyTyped

    private void lblPCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblPCostoKeyPressed
    if(evt.getKeyChar()==evt.VK_ENTER){
    if(lblPCosto.getText().trim().length()==0){
    lblPCosto.grabFocus();
    }else{
    txtUnidades.grabFocus();
    }    
    }
    }//GEN-LAST:event_lblPCostoKeyPressed

    private void txtUnidadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesKeyPressed
    if(evt.getKeyChar()==evt.VK_ENTER){
    if(txtUnidades.getText().trim().length()==0){
    txtUnidades.grabFocus();
    }else{
     precioCompra = Double.parseDouble(lblPCosto.getText());
     cantidad = Integer.parseInt(txtUnidades.getText());
     daoCompras.addDetalleCompra(modelDetalleCompra, TablaDetalle,ID, descripcion, cantidad,precioCompra, botonQuitar,
                                 lblGasto);
    }    
    }
    }//GEN-LAST:event_txtUnidadesKeyPressed

    private void TablaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDetalleMouseClicked
        filaDetalle = TablaDetalle.getSelectedRow();
        try {
        if(confins.BotonDinamico(TablaDetalle, evt).getName().equals("bq")){
        confins.eliminarFilaTable(modelDetalleCompra, filaDetalle);
        if(TablaDetalle.getRowCount()>0){
        lblGasto.setText( confins.getSum(TablaDetalle, 4)+"0");
        }else{
        lblGasto.setText("0.00");
        lblPCosto.setText("");
        lblPVenta.setText("0.00");
        txtUnidades.setText("");
        }
        }  
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TablaDetalleMouseClicked

    private void TablaDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaDetalleKeyReleased
    if(TablaDetalle.getValueAt(filaDetalle, 2).toString().equals("")){
    JOptionPane.showMessageDialog(null, "ERROR,Antes de modificar la cantidad e importe, debe de ingresar una cantidad",
            "Mensaje del sistema",JOptionPane.ERROR_MESSAGE);
    }else{
    cantidad = Integer.parseInt(TablaDetalle.getValueAt(filaDetalle, 2).toString());
    precioCompra = Double.parseDouble(TablaDetalle.getValueAt(filaDetalle, 3).toString());
    importe = cantidad*precioCompra;
    /// modficando datos de la tabla
    TablaDetalle.setValueAt(importe, filaDetalle, 4);
    lblGasto.setText(confins.getSum(TablaDetalle, 4)+"0");
    }
    }//GEN-LAST:event_TablaDetalleKeyReleased

    private void TablaDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaDetalleKeyPressed
     
    }//GEN-LAST:event_TablaDetalleKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    if(TablaDetalle.getRowCount()>0){
     RUC = txtRucProveedor.getText();
     serieCompra= txt_serie.getText();
     if(RUC.isEmpty()){
      txtRucProveedor.grabFocus();
     }else{
      if(serieCompra.isEmpty()){
       txt_serie.grabFocus();
      }else{
       Guardar_Compras(RUC, serieCompra,FR_MenuPrincipal.NameUsuario);
       ReiniciarTodo();
      }
     }
    }else{
     JOptionPane.showMessageDialog(null, "Error, antes de guardar la compra, debe de listar los productos a comprar",
                                   "Mensaje de Aviso",JOptionPane.ERROR_MESSAGE);
    }  
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    
    private void ReiniciarTodo(){
    confins.clearTable(modelDetalleCompra);
    labelFoto.setIcon(null);txt_serie.setText("");
    importe=0.00;
    lblGasto.setText("0.00");
    }
    
    private void Guardar_Compras(String RUC,String serieCompra,String usuario){
    daoCompras.saveDetalleCompra(RUC, serieCompra, usuario,TablaDetalle);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR_Ingreso_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR_Ingreso_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR_Ingreso_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR_Ingreso_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FR_Ingreso_Productos dialog = new FR_Ingreso_Productos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DatosDetalleCompra;
    private javax.swing.JPanel PanelDetalleCompra;
    private javax.swing.JTable TablaDetalle;
    private org.edisoncor.gui.button.ButtonColoredAction btnCancelar;
    private org.edisoncor.gui.button.ButtonColoredAction btnGuardar;
    private org.edisoncor.gui.button.ButtonRound btnNuevoProducto;
    private org.edisoncor.gui.button.ButtonRound btnSeleccionarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel lblGasto;
    private org.edisoncor.gui.textField.TextFieldRectBackground lblPCosto;
    private javax.swing.JLabel lblPVenta;
    public static javax.swing.JLabel lblProveedorData;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblUsuarioAlmacen;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTable tablaProductos;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtBuscarProducto;
    public static org.edisoncor.gui.textField.TextFieldRectBackground txtRucProveedor;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtUnidades;
    private javax.swing.JTextField txt_serie;
    // End of variables declaration//GEN-END:variables
}
