/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.AppFactura.Vistas.Proveedores;

import com.AppFactura.Controllers.ProveedorDao;
import com.AppFactura.Personalizaciones.Ajustes;
import com.AppFactura.Vistas.Compras.FR_Ingreso_Productos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import org.edisoncor.gui.button.ButtonRound;

/**
 *
 * @author Adrian
 */
public class FR__Lista_Proveedores extends javax.swing.JDialog {
private int eje_X,eje_Y;Point p;int filaSeleccionado;

    DefaultTableModel modelProveedores;
    ButtonRound botonEditar = new ButtonRound();
    ButtonRound botonDelete = new ButtonRound();
    ButtonRound botonSeleccionar = new ButtonRound();
    ProveedorDao daoProveedor = new ProveedorDao();
    Ajustes conf= new Ajustes();
    /**
     * Creates new form FR__Lista_Proveedores
     */
    public FR__Lista_Proveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();initListaProveedores();
    }
    private void initListaProveedores(){
        setResizable(false);
        setLocationRelativeTo(null);
        botonEditar.setText("editar");botonDelete.setText("eliminar");
        botonSeleccionar.setText("Enviar");
        /************************* Name para los botones de la tabla ****************/
        botonSeleccionar.setName("botonE");
        
        /*************************  ***************************************************/
        botonEditar.setBackground(Color.yellow);botonDelete.setBackground(Color.red);
        botonSeleccionar.setBackground(Color.blue);
        modelProveedores = (DefaultTableModel) TablaProveedores.getModel();
        TablaProveedores.setModel(modelProveedores);
        PersonalizaTable();mostrarProveedores();
        TablaProveedores.setRowHeight(37);
    }
    
    private void PersonalizaTable(){
   /**
    * Tabla de lista de Proveedores
    */    
   TablaProveedores.getTableHeader().setBackground(Color.GREEN);
   TablaProveedores.getTableHeader().setForeground(Color.black);
   TablaProveedores.getTableHeader().setFont(new Font("Arial", 16, 16));
   TablaProveedores.getTableHeader().setPreferredSize(new Dimension(43, 43));
   conf.HiddenColumnTable(TablaProveedores, 8);
   conf.HiddenColumnTable(TablaProveedores, 9);
    }
    private void mostrarProveedores(){
    daoProveedor.allProveedores(modelProveedores,botonEditar,botonDelete,
    botonSeleccionar,TablaProveedores);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelHeaderProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblsalir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarProveedor = new org.edisoncor.gui.textField.TextFieldRectBackground();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        PanelHeaderProveedor.setBackground(new java.awt.Color(0, 0, 153));
        PanelHeaderProveedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        PanelHeaderProveedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelHeaderProveedorMouseDragged(evt);
            }
        });
        PanelHeaderProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelHeaderProveedorMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppFactura/Imagenes/provedorr.png"))); // NOI18N
        jLabel1.setText("  Listado de Proveedores");

        lblsalir.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblsalir.setForeground(new java.awt.Color(204, 0, 0));
        lblsalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsalir.setText("X");
        lblsalir.setToolTipText("Cerrar Ventana");
        lblsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelHeaderProveedorLayout = new javax.swing.GroupLayout(PanelHeaderProveedor);
        PanelHeaderProveedor.setLayout(PanelHeaderProveedorLayout);
        PanelHeaderProveedorLayout.setHorizontalGroup(
            PanelHeaderProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderProveedorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelHeaderProveedorLayout.setVerticalGroup(
            PanelHeaderProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblsalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/AppFactura/Imagenes/lupa busqueda.png"))); // NOI18N
        jLabel3.setText("Buscar  : ");

        txtBuscarProveedor.setDescripcion("Buscar por RUC | RAZÓN SOCIAL ");
        txtBuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarProveedorKeyTyped(evt);
            }
        });

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUC", "RAZÓN SOCIAL", "DIRECCIÓN", "PÁGINA WEB", "CORREO", "EDITAR", "ELIMINAR", "SELECCIONAR", "IDPROVEDOR", "IDPERSONA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaProveedores);
        if (TablaProveedores.getColumnModel().getColumnCount() > 0) {
            TablaProveedores.getColumnModel().getColumn(0).setPreferredWidth(140);
            TablaProveedores.getColumnModel().getColumn(1).setPreferredWidth(300);
            TablaProveedores.getColumnModel().getColumn(2).setPreferredWidth(270);
            TablaProveedores.getColumnModel().getColumn(3).setPreferredWidth(200);
            TablaProveedores.getColumnModel().getColumn(4).setPreferredWidth(230);
            TablaProveedores.getColumnModel().getColumn(5).setPreferredWidth(110);
            TablaProveedores.getColumnModel().getColumn(6).setPreferredWidth(110);
            TablaProveedores.getColumnModel().getColumn(7).setPreferredWidth(175);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelHeaderProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelHeaderProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelHeaderProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHeaderProveedorMousePressed
     eje_X = evt.getX();
     eje_Y = evt.getY();
    }//GEN-LAST:event_PanelHeaderProveedorMousePressed

    private void PanelHeaderProveedorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHeaderProveedorMouseDragged
    p= MouseInfo.getPointerInfo().getLocation();
    this.setLocation(p.x-eje_X, p.y-eje_Y);
    }//GEN-LAST:event_PanelHeaderProveedorMouseDragged

    private void lblsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsalirMouseClicked
     dispose();
    }//GEN-LAST:event_lblsalirMouseClicked

    private void TablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedoresMouseClicked
        filaSeleccionado=TablaProveedores.getSelectedRow();
        try {
         if(conf.BotonDinamico(TablaProveedores, evt).getName().equals("botonE")){
         String RUC =TablaProveedores.getValueAt(filaSeleccionado, 0).toString();
         String RAZON_SOCIAL = TablaProveedores.getValueAt(filaSeleccionado, 1).toString();
         FR_Ingreso_Productos.txtRucProveedor.setText(RUC);
         FR_Ingreso_Productos.lblProveedorData.setText(RAZON_SOCIAL);
         dispose();
         }    
        } catch (Exception e) {
        }
    }//GEN-LAST:event_TablaProveedoresMouseClicked

    private void txtBuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProveedorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProveedorKeyReleased

    private void txtBuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProveedorKeyTyped
     
    }//GEN-LAST:event_txtBuscarProveedorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FR__Lista_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FR__Lista_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FR__Lista_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FR__Lista_Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FR__Lista_Proveedores dialog = new FR__Lista_Proveedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHeaderProveedor;
    public static javax.swing.JTable TablaProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsalir;
    private org.edisoncor.gui.textField.TextFieldRectBackground txtBuscarProveedor;
    // End of variables declaration//GEN-END:variables
}
